### ISSUE TITLE
Logout doesnt work when 2 website is open

### ISSUE THREAD

**Issue by wallish** [SAML-Toolkits/php-saml#233]
When i am on one website using saml auth, i can logout/login logout/login ...

After that i open another website, i am automatically authenticate, but logout is not working anymore in both website but i got success response logout from adfs.

```php
        $returnTo = null;
        $paramters = array();
        $nameId = null;
        $sessionIndex = null;
        $nameIdFormat = null;
        if (isset($_SESSION['samlNameId'])) {
            $nameId = $_SESSION['samlNameId'];
        }
        if (isset($_SESSION['samlSessionIndex'])) {
            $sessionIndex = $_SESSION['samlSessionIndex'];
        }
        if (isset($_SESSION['samlNameIdFormat'])) {
            $nameIdFormat = $_SESSION['samlNameIdFormat'];
        }
        // zend auth clear session
        $saml = new Auth_Adapter_Saml();
        $saml->clearIdentity();
        Zend_Session::namespaceUnset($this->session);
        
        $auth->logout($returnTo, $paramters, $nameId, $sessionIndex, false, $nameIdFormat);
```

I dont know what i am doing wrong, can you help me ?

**Comment by pitbulk** [comment]
Why you execute?
```
        $saml = new Auth_Adapter_Saml();
        $saml->clearIdentity();
        Zend_Session::namespaceUnset($this->session);
```
before the logout call?

The local logout should be executed on the Single Logout Service endpoint.

Check the [demo](https://github.com/onelogin/php-saml/blob/master/demo1/index.php) and see how the [processSLO](https://github.com/onelogin/php-saml/blob/master/lib/Saml2/Auth.php#L221) method already take care of closing local session (maybe you will need to pass the callback).

**Comment by wallish** [comment]
I updated my code since i created this ticket.

I clear the session when i get the logout response from idp
