### ISSUE TITLE
Get last Error Code

### ISSUE THREAD

**Issue by MMRah** [SAML-Toolkits/php-saml#253]
Hi,
I am able to  get Last Error Reason by using " getLastErrorReason() " 
How can I get Last Error Code. Is there any method already ?

**Comment by pitbulk** [comment]
There is no method.

in getLastErrorReason will return the error message.

If you want to get the whole Exception (and have access to the error code), you can modify at the is_valid method of [SAMLResponse](https://github.com/onelogin/php-saml/blob/master/lib/Saml2/Response.php#L402), [LogoutRequest](https://github.com/onelogin/php-saml/blob/master/lib/Saml2/LogoutRequest.php#L380) and [LogoutResponse](https://github.com/onelogin/php-saml/blob/master/lib/Saml2/LogoutResponse.php#L188) the line:
```
$this->_error = $e->getMessage();
$debug = $this->_settings->isDebugActive();
if ($debug) {
    echo $this->_error;
}
```
by 
```
$this->_error = $e;
$debug = $this->_settings->isDebugActive();
if ($debug) {
    echo $e->getMessage();
}
```

**Comment by MMRah** [comment]
Hi Thank you very much for the responses. I can do that 
I can also do like `$e->getCode();`
Which will give me code as well.

What I really want to always up-to-date with this repository. If I make custom change on my code I will lose alignment with repository. 

Is there anything can we do ? sent error response as array with code and message? May be something like this `$this->_error['msg'] = $e->getMessage(); $this->_error['code'] = $e->getCode();`

Again, It just only my thought . Can we add this functionality Please ? I really want to be always up-to-date With this repository.

Thank you.

**Comment by pitbulk** [comment]
I think in the new [3.0](https://github.com/onelogin/php-saml/tree/3.0.0) branch makes sense to return the whole Exception instead of just the Message, but 2.X branch will keep as is right now.

Do you want to contribute that change on 3.0?

**Comment by MMRah** [comment]
I will love to do that :D

**Comment by pitbulk** [comment]
@MMRah any progress with that?

**Comment by pitbulk** [comment]
Implemented at https://github.com/SAML-Toolkits/php-saml/commit/b286983edac36a4d003ea62c572bb350587ecc6b
