### ISSUE TITLE
Allow change request ID prefix through settings

### ISSUE THREAD

**Issue by ishenkoyv** [SAML-Toolkits/php-saml#273]
ONELOGIN_ is hardcoded inside OneLogin_Saml2_Utils::generateUniqueID().

**Comment by pitbulk** [comment]
what is the issue with that? Message was generated by OneLogin toolkit so we that prefix to know it was generated by our toolkit.

**Comment by ishenkoyv** [comment]
Does it mean that this library should be used only with your idp? Because there is no any reason to show what libraries we use for our partners/clients (this includes security risks of intrusion with help of bugs in the code)

**Comment by pitbulk** [comment]
Add a prefix to the ID doesnt mean that SAMLResponse only gonna be accepted by OneLogin IdP. That toolkit is compatible with SAML 2.0 IdPs.

The code is public, anyone can audit it before use it so I dont see any security concern here.

Many organizations are using it and is also part of many PHP frameworks SAML extensions (you can review names on packagist).

If you dont want to send that prefix in your software, you can always override the ID generator method in your code. To be honest I dont see the point of adding a new setting parameter to the toolkit to customize the prefix to be used

**Comment by ishenkoyv** [comment]
There is only one problem to add new setting parameter and send it to the uniqid method - it's existing method generateUniqueID which doesn't have any parameters. So a new named method required and generateUniqueID should be marked as deprecated IMHO.
