### ISSUE TITLE
How to handle log out when session has expired at the IDP?

### ISSUE THREAD

**Issue by perifer** [SAML-Toolkits/php-saml#300]
The IDP I've tested with is http://onelogin.com. But if this **is** a problem I'm seeing and not just a bug in my implementation this should relate to any IDP.

When a users log out from my app and the session *has expired* at the IDP (e.g due to session timeout), they are prompted to login at the IDP. The logout flow is interrupted and they are never logged out from my app.

Is there any way to handle this situation? Can you detect if the session of the IDP has expired and in that case just close the session in my app, without redirecting to the IDP? Or can you inform the IDP to not ask for login if the session at the IDP has expired?

**Comment by pitbulk** [comment]
I don't think there is a way to detect that.

**Comment by perifer** [comment]
Thanks for the reply!

The biggest issue as I see it is that you are not logged out from the app. Are there any problems with closing the session before redirecting to  the IDP? I guess so since the recommended flow in SLO seems to be to close the session last in the flow.

Feel free to close this issue though, it's not my intention to turning this into a SAML support channel 😄.

As a side note I found a support document from Suse which have a resolution section which seems to suggest they solved it at the IDP-level. Otherwise the solution seems to try not get into this situation in the first place by limiting the session time.
