### ISSUE TITLE
Issues using certificates with Salesforce as idP

### ISSUE THREAD

**Issue by michuynh** [SAML-Toolkits/php-saml#303]
Hello, 

I'm facing issues with my application using onelogin as SP and Salesforce as idP.
I try to use certificates in order to sign my messages.

1/ Salesforce provides a self-signed certificate when enabling it as idP. 
2/ I mentioned this cert in my properties file. (so I got Salesforce's public key)
3/ I then created my own certificate (with public key) with my private key that I converted to PKCS#8 format as suggested in the comments of the properties file.
4/ I then uploaded my newly created certificate (with public key) in Salesforce.

I try to login but it seems I always receive bad encoded response from Salesforce or is it something else ? Did I miss a step ?

Here is the error I get :

com.onelogin.saml2.exception.ValidationError: SAML Response could not be processed
	at com.onelogin.saml2.authn.SamlResponse.loadXmlFromBase64(SamlResponse.java:127)
	at com.onelogin.saml2.authn.SamlResponse.<init>(SamlResponse.java:105)
	at com.onelogin.saml2.Auth.processResponse(Auth.java:522)
	at com.onelogin.saml2.Auth.processResponse(Auth.java:556)
	at org.apache.jsp.acs_jsp._jspService(acs_jsp.java:156)

Thanks !

Michel.

**Comment by pitbulk** [comment]
Based on the trace, it seems you created a java-saml issue on the php-saml repository.

That said, the error: "SAML Response could not be processed" due error on Auth.java:522 means that the toolkit was not able to read the SAMLResponse parameter sent by Salesforce.

**Comment by michuynh** [comment]
Oh yeah... my mistake...

Yes, it seems like what you said. But I don't understand why. I think I used the certificates right, or am I missing something ? 
Because when I disable the signature check in Salesforce everything works perfectly fine.
It's just when I start to introduce all these certificates and security parameters.

**Comment by michuynh** [comment]
Ok, I installed SAML Tracer and that's what I receive :

As Parameters response :

GET
SAMLResponse: fZJLb+MgFIX/isUePzB2CIpTVe2kitSHNM10MZsKA27oYLB8cdT++xJH0bSbLM/VOffxwerqo7fJQY9gvGtQkeYo0U56Zdxbg/7sNpihq/UKRG8H/lvD4B3oJGYc8LnYoGl03AswwJ3oNfAg+fP1wz0nac6H0QcvvUXJrYZgnAjzmH0IA/Ass14Ku/cQOKO0zN7FQeBjVxy8/2cCfochysHqTEhIo0LJ9rZBr4p2rSJt1S3qqmSqlCQvK1pL1Qm6LBkpKkJrWi+KYklozLjz5jvfoKfHX/dPd9vHV7JcaNbSFrOu6zCVssZsISmu26rqaF4XsiIxDDDprYMgXGgQyQuGc4pJtcsZrxgvizTO+IuSlzPDeDc6EeNzdvyG6zItAaDHIyGUbPzYi3DZfqwYhbvZyrULJnyitVI4RNbYqOHEUukD1irtP1MQVkO0S51K36+ybzuen/g5iDDBT3XjlU5ehJ305X1gdvPrKezdRhirFcrWpyn/G2c/v9L6Cw==
RelayState: https://localhost:8443/java-saml-tookit-jspsample/dologin.jsp
SigAlg: http://www.w3.org/2000/09/xmldsig#rsa-sha1
Signature: YDbnurYEzTkOW7lUPgZmEN3Pu/wtpt4UesoAieDdTTY6Ov0fYIZ45YGG1WWIFVjPvmukL7DcbiiaT4zOeQZgsrkwyaWx0kXyPX8nU1ZFXN6+LZvtDMOxuNL6Yceo1STRjkaRrlIfGKmDR2/O7teQ8pfP2i/2K+FadXDwbQ7m8Y7as4Eq0QKiYKvFMHuzT26bvWsL+tmMkG0l2GIjiOz8xZGQ7SZlLiOD8ZA17Lh64HCUJ+u3DX1VyHW8gNW+U3Rpp64x01ReHyya6VabgOO82grj5tUZqzgR1qGphig3+OxK0nQ6EiwvtOaPoHJPss0+cAGAu+pw5UVsPB+e1eNJTA==

As SAML response :

<samlp:Response xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol"
                Destination="https://localhost:8443/java-saml-tookit-jspsample/acs.jsp"
                ID="_d4fbd2b5f76538d3c203546cdfa493821524646711924"
                InResponseTo="ONELOGIN_297e8b4b-8fff-4cc6-87c4-6b55f4061c52"
                IssueInstant="2018-04-25T08:58:31.924Z"
                Version="2.0"
                > <saml:Issuer xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion"
                 Format="urn:oasis:names:tc:SAML:2.0:nameid-format:entity"
                 >dd-test-idp-saml-dev-ed.my.salesforce.com</saml:Issuer> <samlp:Status> <samlp:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:AuthnFailed" /> </samlp:Status> </samlp:Response>

**Comment by pitbulk** [comment]
I'm not a Salesforce expert, but if something is not properly configured I guess something should be logged in its error logs. Try to review them.

P.S In order to generate self-signed certs, you can use this tool and you won't need to do any transformation:
https://www.samltool.com/self_signed_certs.php

**Comment by pitbulk** [comment]
Check the status part of the SAMLResponse:
```
<samlp:Status>
   <samlp:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:AuthnFailed" />
</samlp:Status>
```
That means that the Authentication process failed at Salesforce.

**Comment by michuynh** [comment]
Yes, I noticed the status you mentioned but I didn't really know what it meant (did I receive their reponse and I couldn't read it ? Did they receive my reponse but couldn't read it ?).
The thing is the toolkit couldn't read it (see error with loadXmlFromBase64). In debug, I just received the encoded response and I could not extract any XML out of it as when trying to decode base64, it came out a string with invalid characters.

**Comment by michuynh** [comment]
Ok, I'm gonna look for Salesforce's logs.

But regarding the toolkit, why don't I get the XML response with the AuthnFailed status? As I said, the toolkit still tries to decode the base-64 encoded response from Salesforce but can't extract the XML. In this case I can't know that it failed, I just know there's a problem with the decoding part. I could see the XML response using you SAML tracer. Not via debugging the code.
Is this normal ?

**Comment by michuynh** [comment]
Ok, thanks. 
I don't know if it has something to do with deflating responses or not, because I've seen some operations like that in the code but this is not handled when decoding the SAML Response.

**Comment by pitbulk** [comment]
I took the SAMLResponseyou shared previously and tried to
decode it using https://www.samltool.com/decode.php and I was able to decode.
I will try now with java-saml

**Comment by michuynh** [comment]
Ok, so when using https://www.samltool.com/decode.php to decode, there is indeed the notion of "Deflated and Encoded XML". In java code, there is the Encoded part (loadXmlFromBase64) but nothing about the Deflated part when handling the SAML Response.

**Comment by pitbulk** [comment]
Ok, java-saml toolkit ACS endpoint is a HTTP-POST endpoint, so no inflated message should arrive.

Verify that you configured properly Salesforce and set the ACS endpoint as HTTP-POST and not HTTP-Redirect.

**Comment by michuynh** [comment]
I don't know exactly what you mean but here is part of my SP configuration in the properties file:
Can you please tell me what I am missing ?

# URL Location where the <Response> from the IdP will be returned
onelogin.saml2.sp.assertion_consumer_service.url = https://localhost:8443/java-saml-tookit-jspsample/acs.jsp

# SAML protocol binding to be used when returning the <Response> or sending the <LogoutRequest>
# message.  Onelogin Toolkit supports for this endpoint the
# HTTP-POST binding only
onelogin.saml2.sp.assertion_consumer_service.binding = urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST

# SSO endpoint info of the IdP. (Authentication Request protocol)
# URL Target of the IdP where the SP will send the Authentication Request Message
onelogin.saml2.idp.single_sign_on_service.url = https://dd-test-idp-saml-dev-ed.my.salesforce.com/idp/endpoint/HttpRedirect
#https://dd-test-idp-saml-dev-ed.my.salesforce.com/idp/endpoint/HttpPost

Thanks!

**Comment by michuynh** [comment]
I don't know exactly what you mean but here is part of my SP configuration in the properties file:
Can you please tell me what I am missing ?


```
onelogin.saml2.sp.entityid = https://localhost:8443/java-saml-tookit-jspsample/metadata.jsp
# Specifies info about where and how the <AuthnResponse> message MUST be
#  returned to the requester, in this case our SP.
# URL Location where the <Response> from the IdP will be returned
onelogin.saml2.sp.assertion_consumer_service.url = https://localhost:8443/java-saml-tookit-jspsample/acs.jsp

# SAML protocol binding to be used when returning the <Response> or sending the <LogoutRequest>
# message.  Onelogin Toolkit supports for this endpoint the
# HTTP-POST binding only
onelogin.saml2.sp.assertion_consumer_service.binding = urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST

# SSO endpoint info of the IdP. (Authentication Request protocol)
# URL Target of the IdP where the SP will send the Authentication Request Message
onelogin.saml2.idp.single_sign_on_service.url = https://dd-test-idp-saml-dev-ed.my.salesforce.com/idp/endpoint/HttpRedirect
#https://dd-test-idp-saml-dev-ed.my.salesforce.com/idp/endpoint/HttpPost
```

**Comment by pitbulk** [comment]
As you see, 
onelogin.saml2.sp.assertion_consumer_service.binding = urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST

So IdP should be sending the SAMLResponse as a POST to the SP ACS URL.
On SAML, only the HTTP-Redirect binding uses inflate/deflate, the HTTP-POST just based64encode.

**Comment by michuynh** [comment]
OK, so my properties file is correct as I use the HTTP-POST binding.

In Salesforce they just ask what the acs url should be... nothing else...

![image](https://user-images.githubusercontent.com/13226959/39256155-78e19e94-48ae-11e8-9b2c-03c0e5b90edc.png)

**Comment by pitbulk** [comment]
Is there a way to set the HTTP-POST binding? 
I see your Salesforce is currently sending SAMLResponse as a GET and Signature data as a GET, this is not supported by the java-saml toolkit.

**Comment by michuynh** [comment]
Yes, here's my AuthnRequest when debugging:

```
<samlp:AuthnRequest xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" ID="ONELOGIN_d60c14fd-5487-4924-8e19-d3f0efa9b231" Version="2.0" IssueInstant="2018-04-25T14:13:32Z" ProviderName="DigDash" Destination="https://dd-test-idp-saml-dev-ed.my.salesforce.com/idp/endpoint/HttpRedirect" ProtocolBinding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" AssertionConsumerServiceURL="https://localhost:8443/java-saml-tookit-jspsample/acs.jsp">
    <saml:Issuer>https://localhost:8443/java-saml-tookit-jspsample/metadata.jsp</saml:Issuer>
    <samlp:NameIDPolicy Format="urn:oasis:names:tc:SAML:2.0:nameid-format:encrypted" AllowCreate="true" />
    <samlp:RequestedAuthnContext Comparison="exact">
        <saml:AuthnContextClassRef>urn:oasis:names:tc:SAML:2.0:ac:classes:urn:oasis:names:tc:SAML:2.0:ac:classes:Password</saml:AuthnContextClassRef>
    </samlp:RequestedAuthnContext>
</samlp:AuthnRequest>
```

It seems right to me

**Comment by pitbulk** [comment]
Maybe is a bug on Salesforce, that it sends the SAMLResponse as a GET, when it invalidates the AuthNRequest.

The first thing you need is to have the AuthNRequest validated, and then verify that the SAMLResponse is sent to the ACS endpoint as a POST.

P.S Sorry but this repository is for reporting issues on OneLogin SAML toolkits, not for offering support on integration on 3rd party IdPs.

**Comment by michuynh** [comment]
Ok, thank you for your time, I'm gonna carry on by myself.

**Comment by pitbulk** [comment]
Try by removing the RequestedAuthnContext requirement by set the following value empty:
```
onelogin.saml2.security.requested_authncontext =
```
Similar the NameIDPolicy that right now is set to encrypted, set it as:
```
onelogin.saml2.sp.nameidformat = urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified
```

**Comment by michuynh** [comment]
I updated my properties file with your settings and it's still not working.

I found the logs in Salesforce regarding connections to the idP (Salesforce) and all I got is this:

![image](https://user-images.githubusercontent.com/13226959/39300109-e807bbf4-494a-11e8-9b97-a14b588e8885.png)

**Comment by pitbulk** [comment]
Ok, Invalid Signature means that Salesforce was not able to validate the Signature of the AuthNRequest.

- Verify that the SP public certificate is properly registered at Salesforce.
- Verify the that the sign algorithm set on the SP is supported by Salesforce

Otherwise, maybe there is an issue with the implementation of the Signature and maybe Salesforce requires the rawurlencode version instead just the urlencoded.

On php-saml I [implemented](https://github.com/onelogin/php-saml/blob/7068f530b696feca8463fbc1bbe644ef52db2d73/lib/Saml2/Auth.php#L611) a way to configure it on settings.
But it is not supported yet on java-saml.

The way to solve is:
- Edit [Utils.java](https://github.com/onelogin/java-saml/blob/master/core/src/main/java/com/onelogin/saml2/util/Util.java) and add a rawUrlEncoder method similar to [urlEncoder](https://github.com/onelogin/java-saml/blob/master/core/src/main/java/com/onelogin/saml2/util/Util.java) method, but instead URLEncoder.encode use [URI](https://stackoverflow.com/questions/7464038/how-to-do-urlencode-rawurlencode-urldecode-rawurldecode-in-java)
- Edit [Auth.java](https://github.com/onelogin/java-saml/blob/master/toolkit/src/main/java/com/onelogin/saml2/Auth.java) and modify the [buildSignature](https://github.com/onelogin/java-saml/blob/master/toolkit/src/main/java/com/onelogin/saml2/Auth.java#L836) method to use the new rawUrlEncoder instead urlEncoder

**Comment by michuynh** [comment]
For your first 2 points:

1/ I think I uploaded my certificate where it is required:

![image](https://user-images.githubusercontent.com/13226959/39308937-11cc4510-4967-11e8-9afd-8a27b37aa956.png)

2/ Yes, I checked several times which kind of signature algorithm was handled and every certificate that I use or receive use SHA256withRSA and it doesn't seem like a forbidden/not handled algorithm for Salesforce.

For the code modification, I updated the code as you asked but it's still not working.

**Comment by khanesmail** [comment]
I am also facing same (Invalid Signature) issue, any solution available.
