### ISSUE TITLE
Unable to encrypt assertion issue

### ISSUE THREAD

**Issue by sedfreyatay** [SAML-Toolkits/php-saml#411]
I am getting this error via $auth->getLastErrorReason();
The status code of the Response was not Success, was Responder -> Unable to encrypt assertion
What could be the issue

Thanks

**Comment by pitbulk** [comment]
That means the IdP rejected the AuthNRequest and is sending back a SAMLResponse whose status is not "Success."  You may review the logs on the IdP side and determine why the AuthNRequest was rejected.
