### ISSUE TITLE
SAML Response not found, Only supported HTTP_POST Binding

### ISSUE THREAD

**Issue by JasonShirley** [SAML-Toolkits/php-saml#429]
I'm trying to implement an SP for a client. When I run this on my dev server, it runs perfect. When I run it on the prod server though, I get the error message 
``` SAML Response not found, Only supported HTTP_POST Binding ``` and a 500 error.

I have the binding set in the SP to ``` urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST ``` . 

When I run the program and initialize OneLogin_Saml2_Auth, $_POST is empty. What steps should I take to try and fix this?

**Comment by pitbulk** [comment]
Maybe the IdP is not sending properly the SAMLResponse in a POST parameter.

Download and install [SAML Tracer](https://addons.mozilla.org/en-US/firefox/addon/saml-tracer/) and use it to record the SAML flow. You can then verify if the data is there.

SAML Tracer howto: https://helpx.adobe.com/enterprise/kb/perform-a-saml-trace.html

**Comment by Deodathus** [comment]
I have the same issue during trying demo1 with this tutorial: `https://developers.onelogin.com/saml/php`. I'm getting `SAMLResponse` in `GET` parameters, instead of getting it in `POST`. How can I fix it?
