### ISSUE TITLE
Support for xmlseclibs aes256-gcm and rsa-oaep-mgf1p

### ISSUE THREAD

**Issue by vanderlee** [SAML-Toolkits/php-saml#432]
The third party package robrichards/xmlseclibs' latest revision (3.1.0) now supports block cipher aes256-gcm and key transport rsa-oaep-mgf1p.

Is it possible to add an option to use these more secure standards?

**Comment by Michandrz** [comment]
while we're at it, php 7.2 removes the mcrypt module to be compatible with future versions of PHP we should remove the older insecure methods.

**Comment by pitbulk** [comment]
There are plans to integrate such support in a future release.

**Comment by pitbulk** [comment]
3.X and 4.X branches [uses](https://github.com/onelogin/php-saml/blob/3.6.1/composer.json#L19) xmlsec 3.1.1
and GCM support was already added:
https://github.com/SAML-Toolkits/php-saml/commit/7b4d4a6df94a782b4688ebb3d9c6a1334258376c
