### ISSUE TITLE
SSO Shibboleth

### ISSUE THREAD

**Issue by thedarkknight197** [SAML-Toolkits/php-saml#461]
Hi i tryed to use Shibboleth Idp with onelogin as a demo.

I am studyng your SAML Toolckit PHP downloaded from: https://github.com/onelogin/php-saml/archive/master.zip 

I find your response in StackOverflow: https://stackoverflow.com/questions/32848457/onelogin-saml-php-toolkit-can-it-be-used-with-a-none-onelogin-saml-identity-pr but i don't understand how connect Shibboleth Idp, could you help me?

I have created an application on OneLogin As Type: SAML Test Connector (SP Shibboleth)

I selected this because i have to develop an application with IdP Shibboleth of my Customer.

I have configurated settings file as a guide from: https://developers.onelogin.com/saml/php

Atfter login i will be redirect to my demo application and i recive this error: 

`

Warning: DOMDocument::schemaValidate(): Invalid Schema in \\CIGS\DFS1_STAFF\WWW\WEBCIGS\WebMAIN\WebApp\lib\Saml2\Utils.php on line 147
--

1 | 0.0011 | 474840 | {main}( ) | ...\index.php:0
2 | 0.0457 | 1669464 | OneLogin_Saml2_Auth->processResponse( ) | ...\index.php:70
3 | 0.0459 | 1682064 | OneLogin_Saml2_Response->isValid( ) | ...\Auth.php:212
4 | 0.0462 | 1682520 | OneLogin_Saml2_Utils::validateXML( ) | ...\Response.php:146
5 | 0.0462 | 1682704 | schemaValidate ( ) | ...\Utils.php:147

`

**Comment by thedarkknight197** [comment]
My DOMDocument before $res = $dom->schemaValidate($schemaFile);:

`DOMDocument Object ( [doctype] => [implementation] => (object value omitted) [documentElement] => (object value omitted) [actualEncoding] => [encoding] => [xmlEncoding] => [standalone] => 1 [xmlStandalone] => 1 [version] => 1.0 [xmlVersion] => 1.0 [strictErrorChecking] => 1 [documentURI] => my_path [config] => [formatOutput] => [validateOnParse] => [resolveExternals] => [preserveWhiteSpace] => 1 [recover] => [substituteEntities] => [nodeName] => #document [nodeValue] => [nodeType] => 9 [parentNode] => [childNodes] => (object value omitted) [firstChild] => (object value omitted) [lastChild] => (object value omitted) [previousSibling] => [nextSibling] => [attributes] => [ownerDocument] => [namespaceURI] => [prefix] => [localName] => [baseURI] => my_path/demo1/ [textContent] => https://app.onelogin.com/saml/metadata/9aeb4738-0155-4df8-a3e7-34559c20dba1l9V3SMP/2w8kt7I4UrN54oSto2s=KUrMPZie5XJWY3fufuUzmEb9cqzDLy0gsZnTCrBxeEFkMUhnrL7xFD7Ep9CM6xsbR4PuqM9lghLoFxpBaoJtqia0uTL36BYd0wfvPh2MM2XIuzLC3r4B24s9dUg0S+nQ09l04ntGuW9jB+YRLq7IX0ZP8lhVAWXe2zJV8AjBASbp+I1JWJ+RNuQCbtf/MzGHiw62F5ZZuC0xfjdKIoCEk1/sD+riEad17jKFH9LtH0+y6PTXnUi86hiS3aGu1BLsYRd5Pr+h2mKWD+4I1zGmX6scvgcyVEQ6wlpb3ztMQ1m5vlWObWnZTYg7x4P/4KQhNkP+jGPM5Qx5gLxl+GNmaQ==MIID2DCCAsCgAwIBAgIUQ8IBfXGbobc5QYVi+o0GDm9K/RUwDQYJKoZIhvcNAQEFBQAwRDEPMA0GA1UECgwGbXZiZGV2MRUwEwYDVQQLDAxPbmVMb2dpbiBJZFAxGjAYBgNVBAMMEU9uZUxvZ2luIEFjY291bnQgMB4XDTIxMDExMzExMDAwMloXDTI2MDExMzExMDAwMlowRDEPMA0GA1UECgwGbXZiZGV2MRUwEwYDVQQLDAxPbmVMb2dpbiBJZFAxGjAYBgNVBAMMEU9uZUxvZ2luIEFjY291bnQgMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA6W5LQupG1AUrGOCqNe829h5Mlb5q/Ag1NC2Xp+AKfT1+RDeKpUTljk0MXGbGIwbiXDSZYqI55Es+2ATg+SNghQF+fUfrMVzbj2beYVskVSHHXhgd5yKU86WYTpKj7W+Y0JQF3t051Ne3n0Inf/L0kFwK4ZeYhg2U3Sk34sOWiYsnCPB0vX6lNHMiH9xLrgve3ST37hC6It6/yDeYGMI6OB1Yrh0LM3NgYJ2F/cqp9wlCsMhI5JmdvopyC1UwovMS7C/9pTUksNEnQbYmsv/A8ytUxUvjtChlz22jw1HNI8BCsrqiwxxOXeTm7ipSiz12K1yumgZx7erth4PPqX8AUQIDAQABo4HBMIG+MAwGA1UdEwEB/wQCMAAwHQYDVR0OBBYEFO80V94MzoRFI2TgMLOQpLn0U6nQMH8GA1UdIwR4MHaAFO80V94MzoRFI2TgMLOQpLn0U6nQoUikRjBEMQ8wDQYDVQQKDAZtdmJkZXYxFTATBgNVBAsMDE9uZUxvZ2luIElkUDEaMBgGA1UEAwwRT25lTG9naW4gQWNjb3VudCCCFEPCAX1xm6G3OUGFYvqNBg5vSv0VMA4GA1UdDwEB/wQEAwIHgDANBgkqhkiG9w0BAQUFAAOCAQEAWgORwQ+DqVCPDWMVehj84yTlwfEzX4as1lJwf54Z0pAPp+M0qB0rIYy3a03Hn0EIDKtfasE5eBnJp2kBC4SzP9QqQTh7AWLs374bcT8tjKnDDP2XG6gzs3iqjwdbPm7R8j7cQ7LupZ+EHKGrUHvaV3fPOgMv6b8gIcShv1d01k87T9rCYtZ9DqcMdtzSXoAn+8QIUHbY7qSD9IRtQNznJsIKdwgzgGzZ5JzkbBGPkns6fjwXhODQRLxD+Qxc8ja6Zi+OcAa3i6n4fNeCpEeg1vfLlMOCEPc/RF6F8PG6vSXOrvzDAiWdV1xlaiszkuqzF1uVBK8WY+r7X5a/j+tHfw==https://app.onelogin.com/saml/metadata/9aeb4738-0155-4df8-a3e7-34559c20dba1my_emailmy_path/metadata.phpurn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransportMichelemy_emailmy_surnamemy_email ) `

$schemaFile is in: my_path\lib\Saml2/schemas/saml-schema-protocol-2.0.xsd

**Comment by pitbulk** [comment]
Hi,

You get that error because you should not be providing a valid SAMLResponse to the ACS endpoint of the toolkit.

You are using Shibboleth as your IdP, so you don't need OneLogin to act as your IdP, so you don't need to configure any "SAML Test Connector (SP Shibboleth)" at OneLogin platform. That connector is used to connect a Shibolleth SP, but you mentioned that your goal is to connect Shibboleth IdP and the OneLogin PHP SAML Toolkit.

All you need to do is to publish the demo1 with Apache or Nginx. and configure the [SAML Settings file](https://github.com/onelogin/php-saml/blob/master/demo1/settings_example.php) and save it as settings.php
There you need to register the Shibboleth IdP metadata info.
Then access to the metadata.php file of the toolkit, and register this SP Metadata at Shibboleth IdP.
Review at Shibboleth IdP documentation how to obtain the IdP metadata and how register the SP metadata.

**Comment by thedarkknight197** [comment]
Thank you so much!

Yesterday I tried to connect to Shibboleth OneLogin's IdP because the customer idp information i don't have yet.

So the only action that i have to do is setting settings.php file with the information about my IdP?

I tried to connect to OneLogin's IdP Shibboleth, configuring the configuration IdP serivice as https://developers.onelogin.com/saml/php point 4 section 10.
And registered in settings.php file as https://developers.onelogin.com/saml/php section 3.

In Configuration OneLogin IdP Setting i configured:
- Login url: my_site/demo1/index.php
- ACS (consumer) url: my_site/demo1/index.php?acs
- SAML Recipient: my_site/demo1/index.php
- SAML Single Logout Url: my_site/demo1/index.php?sls
- ACS (consumer) url validator: .*
- Audience: my_site/demo1/metadata.php

What change i have to do to work with Shibboleth OneLogin's IdP?
And when i change idP I have only to change the SAML Setting file, correct?

**Comment by pitbulk** [comment]
If you are trying to connnect with OneLogin platform, use the "Advanced SAML Test Connector" instead of the "Shibboleth OneLogin's IdP".

If you registered the SP metadata in the connector, then you need to register the IdP metedata on the PHP SAML settings: [settings.php](https://github.com/onelogin/php-saml/blob/master/settings_example.php) file.

**Comment by thedarkknight197** [comment]
Ok i try the advancedSamlTestConnector. I have a question about it: the SP is my web site. What i have to write in var entityId? And I don't have the x509cert and privateKey, can i don't assign any value?

**Comment by pitbulk** [comment]
The fact of assign a PrivateKey and Public cert to the SP is optional and you only need to assign them if you plan to sign the messages sent by the SP or you require the SAMLResponse Assertion to be encrypted. You can use self-signed certs, this tool creates it:
https://www.samltool.com/self_signed_certs.php

Please review the documentation of this toolkit, everything is described on it.

**Comment by thedarkknight197** [comment]
I try the new settings.php file, i renamed settings in settingsInfo. But i have the same problem: 

Warning: DOMDocument::schemaValidate(): Invalid Schema in \\CIGS\DFS1_STAFF\WWW\WEBCIGS\WebMAIN\WebApp\lib\Saml2\Utils.php on line 151

This is my settings.php: https://www.codepile.net/pile/7AYNeWjy

**Comment by thedarkknight197** [comment]
Using OneLogin: SAML Test Connector (Advanced) it work correctly. I don't understand why it not work qui Shibboleth SAML Response

**Comment by thedarkknight197** [comment]
> The fact of assign a PrivateKey and Public cert to the SP is optional and you only need to assign them if you plan to sign the messages sent by the SP or you require the SAMLResponse Assertion to be encrypted. You can use self-signed certs, this tool creates it:
> https://www.samltool.com/self_signed_certs.php
> 
> Please review the documentation of this toolkit, everything is described on it.

i find the problem, i think. 

OneLogin return a Response XML with ds data, that it isn't in example on onelogin: https://www.samltool.com/generic_sso_res.php 

In xml i have:
<ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
<ds:SignedInfo>
<ds:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
<ds:SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/>
<ds:Reference URI="#pfx4a8b2268-73c7-a440-75aa-fe4f2aa782c5">
<ds:Transforms>
<ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>
<ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
</ds:Transforms>
<ds:DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/>
<ds:DigestValue>Yx20g0pbvuMcH7uIl6ccwD308xA=</ds:DigestValue>
</ds:Reference>
</ds:SignedInfo>
<ds:SignatureValue>signature</ds:SignatureValue>
<ds:KeyInfo>
<ds:X509Data>
<ds:X509Certificate>x509 cert</ds:X509Certificate>
</ds:X509Data>
</ds:KeyInfo>
</ds:Signature>

**Comment by thedarkknight197** [comment]
here are my XML response, it is what i recive from onelogin: https://www.cigs.unimo.it/webapp/demo1/output.xml

**Comment by thedarkknight197** [comment]
And OneLogin Validator result: 

The response was received at https://www.cigs.unimo.it/webapp/demo1/index.php?acs instead of https://www.cigs.unimo.it/webapp/demo1/index.php
A valid SubjectConfirmation was not found on this Response
Signature validation failed. Reference validation failed

**Comment by pitbulk** [comment]
You need to set as ACS URL:

https://www.cigs.unimo.it/webapp/demo1/index.php?acs

**Comment by thedarkknight197** [comment]
this is my settings:

$spBaseUrl = 'https://www.cigs.unimo.it/webapp'; //or http://<your_domain>

    $settingsInfo = array (
        'debug' => true,
        'sp' => array (
            'entityId' => $spBaseUrl.'/demo1/metadata.php',
            'assertionConsumerService' => array (
                'url' => $spBaseUrl.'/demo1/index.php?acs',
            ),
            'singleLogoutService' => array (
                'url' => $spBaseUrl.'/demo1/index.php?sls',
            ),
            'NameIDFormat' => 'urn:oasis:names:tc:SAML:1.1:nameid-format:info@mvbdev.cloud',
        ),
        'idp' => array (
            'entityId' => 'urlentry/metadata',
            'singleSignOnService' => array (
                'url' => '/saml2/http-post/sso/',
            ),
            'singleLogoutService' => array (
                'url' => '/saml2/http-redirect/slo/',
            ),
            'x509cert' => 'cert',
        ),
    );

I set acs, this is incorrect?

**Comment by jewelsd1967** [comment]
What is this?On Jan 18, 2021 02:57, Michele Vitiello Bonaventura <notifications@github.com> wrote:
this is my settings:
$spBaseUrl = 'https://www.cigs.unimo.it/webapp'; //or http://<your_domain>
$settingsInfo = array (
    'debug' => true,
    'sp' => array (
        'entityId' => $spBaseUrl.'/demo1/metadata.php',
        'assertionConsumerService' => array (
            'url' => $spBaseUrl.'/demo1/index.php?acs',
        ),
        'singleLogoutService' => array (
            'url' => $spBaseUrl.'/demo1/index.php?sls',
        ),
        'NameIDFormat' => 'urn:oasis:names:tc:SAML:1.1:nameid-format:info@mvbdev.cloud',
    ),
    'idp' => array (
        'entityId' => 'urlentry/metadata',
        'singleSignOnService' => array (
            'url' => '/saml2/http-post/sso/',
        ),
        'singleLogoutService' => array (
            'url' => '/saml2/http-redirect/slo/',
        ),
        'x509cert' => 'cert',
    ),
);

I set acs, this is incorrect?

**Comment by pitbulk** [comment]
That setting at the toolkit side is ok, you need to set the right value at the OneLogin connector

**Comment by thedarkknight197** [comment]
> That setting at the toolkit side is ok, you need to set the right value at the OneLogin connector

Hi i recived my customer inner-metadata.xml.

I am setting my settings file. In this file exist an entry for this domain, because is already used for login. 

How work redirect? 

When i try to login on shibboleth login page, i receive that the request is not supported,
The application that you connected is not registered for use trough this service.

i have to add and entry for my domain/folder also that the domain is already registered?

My new IDP:
'idp' => array (
            'entityId' => 'http://www.cigs.unimo.it/shibboleth',
            'singleSignOnService' => array (
                'url' => 'https://idp.unimore.it/idp/profile/Shibboleth/SSO',
            ),
            'singleLogoutService' => array (
                'url' => 'http://www.cigs.unimo.it/Shibboleth.sso/SLO/POST',
            ),
            'x509cert' => 'CERT',
        ),

the entityId i take from:
"
<md:EntityDescriptor xmlns:md="urn:oasis:names:tc:SAML:2.0:metadata" entityID="http://www.cigs.unimo.it/shibboleth">
    <md:SPSSODescriptor protocolSupportEnumeration="urn:oasis:names:tc:SAML:2.0:protocol urn:oasis:names:tc:SAML:1.1:protocol urn:oasis:names:tc:SAML:1.0:protocol">
"

For Logout Service i use:
"
<md:SingleLogoutService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="http://www.cigs.unimo.it/Shibboleth.sso/SLO/POST"/>
"

And for Login:
"
<SingleSignOnService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect" Location="https://idp.unimore.it/idp/profile/SAML2/Redirect/SSO"/>
"

**Comment by thedarkknight197** [comment]
*and for Login:
"
<SingleSignOnService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect" Location="https://idp.unimore.it/idp/profile/SAML2/Redirect/SSO"/>
"

**Comment by thedarkknight197** [comment]
My service when i do login it need in get: ?execution=e1s1 with number that change every try.

The library doing redirect with GET parameter: SAMLRequest=XXXXXX how could i change it?

**Comment by pitbulk** [comment]
You got
```
The response was received at https://www.cigs.unimo.it/webapp/demo1/index.php?acs instead of https://www.cigs.unimo.it/webapp/demo1/index.php
```
because at the IdP you registered wrong SP ACS endpoint, or the IdP removed the query parameters, if that is the case, you could always use demo2 which has the endpoints in different files, so no query parameter is required.

**Comment by thedarkknight197** [comment]
Hi my customer registered my application in his Shibboleth login, but whene i try to login here, i recive an error in Customer IdP

What i have to do? https://app.cigs.unimore.it/demo1/

**Comment by thedarkknight197** [comment]
Hi i have a correct configuration of shibboleth. I can login on shibboleth idp and it redirect me to my page after login.
But OneLogin now tell me this error:
"
failed to load external entity "/CIGS/DFS1_STAFF/WWW/WEBCIGS/WebMAIN/WebApp/lib/Saml2/schemas/xmldsig-core-schema.xsd" Element '{http://www.w3.org/2001/XMLSchema}import': Failed to locate a schema at location '/CIGS/DFS1_STAFF/WWW/WEBCIGS/WebMAIN/WebApp/lib/Saml2/schemas/xmldsig-core-schema.xsd'. Skipping the import. failed to load external entity "/CIGS/DFS1_STAFF/WWW/WEBCIGS/WebMAIN/WebApp/lib/Saml2/schemas/xenc-schema.xsd" Element '{http://www.w3.org/2001/XMLSchema}import': Failed to locate a schema at location '/CIGS/DFS1_STAFF/WWW/WEBCIGS/WebMAIN/WebApp/lib/Saml2/schemas/xenc-schema.xsd'. Skipping the import. Element '{http://www.w3.org/2001/XMLSchema}element', attribute 'ref': The QName value '{http://www.w3.org/2001/04/xmlenc#}EncryptedData' does not resolve to a(n) element declaration. Element '{http://www.w3.org/2001/XMLSchema}element', attribute 'ref': The QName value '{http://www.w3.org/2001/04/xmlenc#}EncryptedKey' does not resolve to a(n) element declaration. Invalid SAML Response. Not match the saml-schema-protocol-2.0.xsd
invalid_response

Invalid SAML Response. Not match the saml-schema-protocol-2.0.xsd

Not authenticated"

With SAML Traker i See correct authentication about my user with my data:
"
<saml2:AuthnStatement AuthnInstant="2021-02-04T08:52:10.281Z"
                              SessionIndex="_683d7dcca29XXXX"
                              >
            <saml2:SubjectLocality Address="XXX.XXX.XXX.XXX" />
            <saml2:AuthnContext>
                <saml2:AuthnContextClassRef>urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport</saml2:AuthnContextClassRef>
            </saml2:AuthnContext>
        </saml2:AuthnStatement>
        <saml2:AttributeStatement>
            <saml2:Attribute FriendlyName="givenName"
                             Name="urn:oid:2.5.4.42"
                             NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri"
                             >
                <saml2:AttributeValue xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                                      xsi:type="xsd:string"
                                      >XXXX</saml2:AttributeValue>
            </saml2:Attribute>
            <saml2:Attribute FriendlyName="ou"
                             Name="urn:oid:2.5.4.11"
                             NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri"
                             >
                <saml2:AttributeValue xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                                      xsi:type="xsd:string"
                                      >people</saml2:AttributeValue>
                <saml2:AttributeValue xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                                      xsi:type="xsd:string"
                                      >Esterni</saml2:AttributeValue>
            </saml2:Attribute>
            <saml2:Attribute FriendlyName="sn"
                             Name="urn:oid:2.5.4.4"
                             NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri"
                             >
                <saml2:AttributeValue xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                                      xsi:type="xsd:string"
                                      >XXXX</saml2:AttributeValue>
            </saml2:Attribute>
            <saml2:Attribute FriendlyName="cn"
                             Name="urn:oid:2.5.4.3"
                             NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri"
                             >
                <saml2:AttributeValue xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                                      xsi:type="xsd:string"
                                      >XXXX XXXX</saml2:AttributeValue>
            </saml2:Attribute>
            <saml2:Attribute FriendlyName="uid"
                             Name="urn:oid:0.9.2342.19200300.100.1.1"
                             NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri"
                             >
                <saml2:AttributeValue>XXXXXX</saml2:AttributeValue>
            </saml2:Attribute>
            <saml2:Attribute FriendlyName="eduPersonScopedAffiliation"
                             Name="urn:oid:1.3.6.1.4.1.5923.1.1.1.9"
                             NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri"
                             >
                <saml2:AttributeValue xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                                      xsi:type="xsd:string"
                                      >XXX@XXXX.it</saml2:AttributeValue>
            </saml2:Attribute>
            <saml2:Attribute FriendlyName="unimoreDiporg2"
                             Name="urn:oid:1.3.6.1.4.1.13331.9.9.0.5.1.12"
                             NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri"
                             >
                <saml2:AttributeValue xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                                      xsi:type="xsd:string"
                                      >{1}{020067}CENTRO INTERDIPARTIMENTALE GRANDI STRUMENTI</saml2:AttributeValue>
            </saml2:Attribute>
            <saml2:Attribute FriendlyName="unimoreDiporg4"
                             Name="urn:oid:1.3.6.1.4.1.13331.9.9.0.5.1.14"
                             NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri"
                             >
                <saml2:AttributeValue xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                                      xsi:type="xsd:string"
                                      >{1}{020067}CENTRO INTERDIPARTIMENTALE GRANDI STRUMENTI</saml2:AttributeValue>
            </saml2:Attribute>
            <saml2:Attribute FriendlyName="eduPersonPrincipalName"
                             Name="urn:oid:1.3.6.1.4.1.5923.1.1.1.6"
                             NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri"
                             >
                <saml2:AttributeValue>XXX@XXXX.it</saml2:AttributeValue>
            </saml2:Attribute>
        </saml2:AttributeStatement>
"

**Comment by pitbulk** [comment]
```
Failed to locate a schema at location '/CIGS/DFS1_STAFF/WWW/WEBCIGS/WebMAIN/WebApp/lib/Saml2/schemas/xmldsig-core-schema.xsd
```
The toolkit is not able to read that file, required in order to validate the SAMLResponse.

**Comment by thedarkknight197** [comment]
demo1 is in my swebapp floder that is loaded form IIS to serve the request from app.cigs.unimore.it.
web app is serve from app.cigs.unimore.it, to do accesso to demo1 i use app.cigs.unimore.it/demo1, the lib is in corrected location at webapp/lib/Saml2/schemas/files.

For now i have resolved doing comment from line 148 to 161 in Utils.php file in lib/Sam2 to ignore the validation of SAML2 Response. After i will extend your class, coping method content and removing the validation.

Now i see my data of user logged on index.php.

Now i am working to do logout with signed request.

Thank you for you support :)

**Comment by thedarkknight197** [comment]
i have addedd in settings.php in the configuration this array after baseurl:

'security' =>array(
        // Indicates whether the <samlp:logoutRequest> messages sent by this SP
        // will be signed.
        'logoutRequestSigned' => true,

        // Indicates whether the <samlp:logoutResponse> messages sent by this SP
        // will be signed.
        'logoutResponseSigned' => true,
    ),


because i tried this withouth success:
The settings files described (settings.php and advanced_settings.php) are loaded by the toolkit if no other array with settings info is provided in the constructor of the toolkit. Let's see some examples.

// Initializes toolkit with settings.php & advanced_settings files.
$auth = new OneLogin_Saml2_Auth();
//or
$settings = new OneLogin_Saml2_Settings();

// Initializes toolkit with the array provided.
$auth = new OneLogin_Saml2_Auth($settingsInfo);
//or
$settings = new OneLogin_Saml2_Settings($settingsInfo);
You can declare the $settingsInfo in the file that contains the constructor execution or locate them in any file and load the file in order to get the array available as we see in the following example:

<?php

require_once 'custom_settings.php';  // The custom_settings.php contains a
                                     // $settingsInfo array.

$auth = new OneLogin_Saml2_Auth($settingsInfo);
