### ISSUE TITLE
SSO Logout ADFS issue

### ISSUE THREAD

**Issue by shibon-lal** [SAML-Toolkits/php-saml#484]
Hi
Facing issue with **adfs/ls/?wa=wsignout1.0** logout
I am trying to do logout from SSO and my application using **processSLO**  function
But this gives me response code as 302 (redirect instead of 200)
While using oneLogin it is working fine (response is 200 and the application cookie is deleted)

Issue is i can't able to remove cookie created by application since it is throwing 302 
This will always redirect me to SSO logout page, even if i paste application URL in browser

<img width="688" alt="SSO-requests" src="https://user-images.githubusercontent.com/40288623/130005028-9743438c-da8a-479f-a8f5-c05447872d24.PNG">

**Comment by pitbulk** [comment]
-adfs/ls/?wa=wsignout1.0   <-- This is not a SAML Single Logout Service endpoint

Try to just use the url without the ?wa=wsignout1.0

**Comment by pitbulk** [comment]
@shibon-lal is the SLO working?

**Comment by pitbulk** [comment]
The user flow ends in the entity that initiated the SLO action. If it was at the IdP, it should end at the IdP.
If the SLO was initiated at the SP, need to end at such SP... but take in mind that some apps forces the SAML login, so after the SLO, maybe a new AuthNRequest happens and the user see the IdP's login form.
