### ISSUE TITLE
Sign AuthnRequest

### ISSUE THREAD

**Issue by lawrencedesign** [SAML-Toolkits/php-saml#504]
Hi All!

How can I config my SP to put a signature inside the AuthnRequest?
There is a setting called:  authnRequestsSigned, but I can't make it do the job. 

Thanks.

**Comment by pitbulk** [comment]
In addition to the authnRequestsSigned flag, you will need to provide at the settings the SP private key and SP public cert.
https://github.com/onelogin/php-saml/blob/master/settings_example.php#L64

**Comment by lawrencedesign** [comment]
I provided the SP private key and Cert. Nothing happened. Check the request xml and no signature fields. I have to put the signature inside the request. 
I search inside your code and no sign function for authnrequest, just for metadata.

**Comment by pitbulk** [comment]
AuthNRequest is sent using HTTP-Redirect binding, have you verified here is no Signature GET parameter?

**Comment by lawrencedesign** [comment]
I have to send AuthnRequest with using HTTP-POST binding

**Comment by pitbulk** [comment]
The toolkit does not support to send AuthNRequest via HTTP-POST, but you can extend the AuthNRequest class.

Take a look at: https://github.com/onelogin/php-saml/pull/422
