### ISSUE TITLE
SSO config for multiple users

### ISSUE THREAD

**Issue by html5maker** [SAML-Toolkits/php-saml#505]
Is it possible to use this library to allow my customers/users to configure their own SSO?
Basically I want to allow my customers/users to input their own x.509 Certificate, IDP Entity id, SAML 2 endpoint.

**Comment by kynx** [comment]
Yes, we do pretty much exactly this, although we use a common x509 cert - I wouldn't trust our users to generate one ;)

Quite how you do it will depend a lot on your application / framework. But it goes something like this:

* Each tenant has different endpoints URLs for the `acs`, `sls` and `metadata` so we know which one is being requested from the URL
* We store the IdP part of the settings in the database. The tenant endpoint merges this with the "common" part of the config once it knows which tenant is requesting the service
* The settings are then used to construct an `Auth` instance to process the response etc
* We have a simple UI for entering the IdP metadata URL and / or uploading it plus downloading the SP metadata

I'm sure I've missed a gotcha or two, but that's the idea. It works well. Spend some time validating the metadata the users are entering and provide detailed error message tho - users are very fond of uploading their SP metadata to the IdP field and visa-versa and aren't good at figuring out why that doesn't work.
