### ISSUE TITLE
Add Custom Exension to AuthNRequest

### ISSUE THREAD

**Issue by djstini** [SAML-Toolkits/php-saml#508]
Hi,

I need to add a custom extension to the AuthNRequest, i have the xml already, just have to jam it in with the request somehow.

Is there an easy way to do this or will i have to extend the Request Class?

Cheers!

**Comment by pitbulk** [comment]
you need to extend the AuthNRequest and Auth class

**Comment by pitbulk** [comment]
See https://github.com/SAML-Toolkits/php-saml/issues/533
