### ISSUE TITLE
Validation error on Wordpress site via simplesaml plugin

### ISSUE THREAD

**Issue by redlik** [SAML-Toolkits/php-saml#517]
I'm getting this error via Wordpress fatal error alert:
`An error of type E_ERROR was caused in line 103 of the file /wp-content/plugins/wp-saml-auth/vendor/onelogin/php-saml/src/Saml2/Response.php. Error message: Uncaught OneLogin\Saml2\ValidationError: SAML Response could not be processed in /code/wp-content/plugins/wp-saml-auth/vendor/onelogin/php-saml/src/Saml2/Response.php:103`
The logs don't show any particular reason for this error so may be some bots trying to pass through wordpress login ???

**Comment by pitbulk** [comment]
@redlik   This issue should be opened at the [wp-saml-auth issue tracker](https://github.com/pantheon-systems/wp-saml-auth/issues).

The "SAML Response could not be processed" error [is raised in the toolkit](https://github.com/SAML-Toolkits/php-saml/blob/4.x-dev/src/Saml2/Response.php#L104) when the value provided as SAMLResponse does not validate against the XSD.

You should double check and see what value was provided to the toolkit.
