### ISSUE TITLE
The response was received at HTTP instead of HTTPS

### ISSUE THREAD

**Issue by Cy-Beard** [SAML-Toolkits/php-saml#530]
I am referencing The response was received at http:// instead of https:// and reverse proxy issue #430
I am getting this error but i am using the PYthon-Saml plugin. The answer was said to use setVARsProxy to true. Does anyone know how to do that on the python side?
I am running a python web server with a ssl plugin and utilizing Azure SSO. 
I can paste config files if needed.

**Comment by Cy-Beard** [comment]
is there anyone that could help me with this?

**Comment by pitbulk** [comment]
If you are using python-saml or python3-saml, not sure why you are opening an issue on the php-saml tracker.

At the PHP SAML Toolkit, you can use the method setSelfProtocol or setBaseURLPath as documented at the [url-guessing-methods](https://github.com/SAML-Toolkits/php-saml#url-guessing-methods) section of the documentation. Or try with the setProxyVars(true) that you already mentioned.

At the Python SAML Toolkit, you provide the request_data to the [Auth](https://github.com/SAML-Toolkits/python3-saml/blob/master/src/onelogin/saml2/auth.py#L40) object, so all you need to do is to prepare the request_data and make sure you adjust the protocol info properly. See for example the [Django demo example](https://github.com/SAML-Toolkits/python3-saml/blob/master/demo-django/demo/views.py#L17)
```
def prepare_django_request(request):
    # If server is behind proxys or balancers use the HTTP_X_FORWARDED fields
    result = {
        'https': 'on' if request.is_secure() else 'off',
        'http_host': request.META['HTTP_HOST'],
        'script_name': request.META['PATH_INFO'],
        'get_data': request.GET.copy(),
        # Uncomment if using ADFS as IdP, https://github.com/onelogin/python-saml/pull/144
        # 'lowercase_urlencoding': True,
        'post_data': request.POST.copy()
    }
    return result
```

In your case, you should set:
```
'https': 'on' 
```
and don't rely on  request.is_secure()
