### ISSUE TITLE
I can't send a SAML:Extension in Login request

### ISSUE THREAD

**Issue by elmascato** [SAML-Toolkits/php-saml#533]
I am trying to send additional parameters with the login but I am not able to as the only way seems to be via URL. As this is the only possible way, SAML:Extension has no values as it is not possible to send array. Any solution to this?

**Comment by pitbulk** [comment]
[samlp:Extensions](http://www.datypic.com/sc/saml2/e-samlp_Extensions.html) is an optional element of the [AuthNRequest](http://www.datypic.com/sc/saml2/e-samlp_AuthnRequest.html) element.

The toolkit does not support right now the inclusion of such element, but you could extend the [AuthNRequest constructor](https://github.com/SAML-Toolkits/php-saml/blob/4.x-dev/src/Saml2/AuthnRequest.php#L53). adding an extension array 

```
__construct(\OneLogin\Saml2\Settings $settings, $forceAuthn = false, $isPassive = false, $setNameIdPolicy = true, $nameIdValueReq = null, $extension = [])
```

Then define a $extensionStr with the content for the extension section
```
$extensionStr = "";
if (!empty($extension)) {

$extensionStr += "<samlp:Extensions>";

// Loop over the elements of the extension and include them

$extensionStr +=  "</samlp:Extensions>";
}


```

And redefine the AuthNRequest content to include such value

```
$request = <<<AUTHNREQUEST
<samlp:AuthnRequest
    xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol"
    xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion"
    ID="$id"
    Version="2.0"
{$providerNameStr}{$forceAuthnStr}{$isPassiveStr}
    IssueInstant="{$issueInstant}"
    Destination="{$destination}"
    ProtocolBinding="{$spData['assertionConsumerService']['binding']}"
    AssertionConsumerServiceURL="{$acsUrl}">
    <saml:Issuer>{$spEntityId}</saml:Issuer>{$subjectStr}{$extensionStr}{$nameIdPolicyStr}{$requestedAuthnStr}
</samlp:AuthnRequest>
AUTHNREQUEST;
```
