### ISSUE TITLE
Not found metadata.php

### ISSUE THREAD

**Issue by cabezacba** [SAML-Toolkits/php-saml#534]
Good morning, I have the following problem to authenticate with SAML, the metadata.php file

Identity Provider Entity ID:

http://url.com/saml2/idp/metadata.php

Does not appear.
How do I make it generate?
Thank you

**Comment by pitbulk** [comment]
The "Identity Provider Entity ID" is a value that needs to be provided by the IdP.

If you are looking for the metadata.php file which generates the SP metadata, you can find it inside the [demo1 folder](https://github.com/SAML-Toolkits/php-saml/blob/4.x-dev/demo1/metadata.php)
