### ISSUE TITLE
Response::validateNumAssertions() is failing in some cases

### ISSUE THREAD

**Issue by yukman69** [SAML-Toolkits/php-saml#535]
In some cases the validateNumAssertions validation fails (matching Assertion nodes not in root document).
Attached is one example of response causing validation error:

[saml myid response.txt](https://github.com/onelogin/php-saml/files/9714399/saml.myid.response.txt)

**Comment by pitbulk** [comment]
This is because the SAMLResponse you shared have 2 Assertion elements:
1. Response > Assertion
2. Response > Assertion > Advice > Assertion

and the toolkit only accepts 1 Assertion element.
