### ISSUE TITLE
validUntil parsed incorrectly? 'expire' time in the past after metadata refresh

### ISSUE THREAD

**Issue by mikkorantalainen** [SAML-Toolkits/php-saml#536]
We have an automated update for HAKA federation metadata. The metadata XML file starts with

```
<?xml version="1.0" encoding="UTF-8"?><EntitiesDescriptor xmlns="urn:oasis:names:tc:SAML:2.0:metadata" xmlns:mdattr="urn:oasis:names:tc:SAML:metadata:attribute" xmlns:mdui="urn:oasis:names:tc:SAML:metadata:ui" xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" ID="Haka-20221019133446" Name="urn:mace:funet.fi:haka" validUntil="2022-11-16T11:34:46Z" xsi:schemaLocation="urn:oasis:names:tc:SAML:2.0:metadata saml-schema-metadata-2.0.xsd urn:mace:shibboleth:metadata:1.0 shibboleth-metadata-1.0.xsd http://www.w3.org/2000/09/xmldsig# xmldsig-core-schema.xsd"><ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
<ds:SignedInfo>
...

```

However, when SimpleSAML metadata update is triggered with GET request to `https://.../module.php/cron/cron.php?key=SECRET&tag=daily` the resulting generated PHP metadata has entry `'expire' => 1666224001,` for every entry in the `$metadata` array.

This expiry time (`1666224001` seconds since UNIX epoch) is `2022-10-20T00:00:01 UTC` which is obviously incorrect given the `validUntil="2022-11-16T11:34:46Z"` attribute of element `EntitiesDescriptor` in the metadata XML file.

The same code and update routine has been working for years so I'm failing to understand why generated PHP files now have incorrect `expire` time. Is this a known bug or have I simply misunderstood something?

**Comment by pitbulk** [comment]
I guess you should register this Issue on simpleSAMLphp repository and not here

**Comment by mikkorantalainen** [comment]
I think the root cause for this issue is https://github.com/simplesamlphp/simplesamlphp/issues/1708
