### ISSUE TITLE
sp acs url empty

### ISSUE THREAD

**Issue by kboumedal** [SAML-Toolkits/php-saml#554]
Would it be possible to let the sp acs url empty, in order to let the idp define the redirect url? 

My case is that I want my sp to redirect automatically users on login.microsoftonline.com, where they can connect with their e-mail address, then microsoft redirect them on their specific tenant according the e-mail (There are multiple). 

Once they are logged in, the idp knows where to redirect them (https://my-idp.com/acs?idp=correct-idp).

Thanks in advance !

**Comment by pitbulk** [comment]
No, the ACS URL needs to be defined at the Service Provider and then registered at the IdP.

SP validates that the generated SAMLResponse from the IdP matches the ACS URL defined at the SP, so this value needs to be defined by the toolkit.

You can make the ACS endpoint dynamic, and based on the parameter provided, read an specific SAML Settings related to an SP defined, and an specific IdP.

**Comment by kboumedal** [comment]
I'm not sure I understand your reply.

How can I make the ACS endpoint dynamic ?

**Comment by pitbulk** [comment]
as simple as accepting an extra parameter on such endpoint, and based on such extra parameter load 1 SAML settings array.

**Comment by kboumedal** [comment]
Ok thanks, I think the problem comes from another bundle which uses yours, I will open an issue in this one !
