### ISSUE TITLE
what steps required to create a IdP initated login with a magicLink in it and redirect to SP

### ISSUE THREAD

**Issue by pentium10** [SAML-Toolkits/php-saml#557]
We have the following requirements:
- we will be the Idp
- user will have a magic link
- IdP initiated login hits us first time
- verify if magicLink checks out, follow with RelayState. 
- end up on the 3rd party website, without username/password prompt

Is there a guide that covers this use case? Is this use case possible with this repo? What shall be developed to make this happen?

**Comment by pitbulk** [comment]
php-saml implements the Service Provider part, not the Identity Provider part.

I recommend you to take a look at [simpleSAMLphp](https://simplesamlphp.org/) instead.
