### ISSUE TITLE
Can PHPSaml be used to implement the IdP?

### ISSUE THREAD

**Issue by mbahnmiller** [SAML-Toolkits/php-saml#560]
Can PHPSaml be used to implement the IdP? I've implemented both SP-initiated and IdP-initiated workflows, where PHPSaml was used on the SP side, but now I need to implement an IdP, and I'd love to use the same library if possible, but I can't seem to find any guidance.

Thanks in advance for the help!

**Comment by pitbulk** [comment]
No, this is only for the SP, it does not generate SAMLResponses.
