### ISSUE TITLE
mcrypt for php8

### ISSUE THREAD

**Issue by lorenzobruni** [SAML-Toolkits/php-saml#564]
Hi, 
I have noticed that `mcrypt `isn't supported in php8.
Is there any consideration to upgrade this project to OpenSSL (or other)? 
Any advice?
Thanks

**Comment by yphoenix** [comment]
Which version are you using. We're v4 of the library with PHP 8.1 with no mcrypt.

**Comment by pitbulk** [comment]
The use of mcrypt was removed on PHP 7.2
