### ISSUE TITLE
Azure Error AADSTS75011. When not having a microsoft account, using a one time passcode.

### ISSUE THREAD

**Issue by djacobs-pewag** [SAML-Toolkits/php-saml#567]
I am using the library to authenticate to Azure and I keep getting an error when a user with no microsoft account, but invited as a guest tries to login to my application. 

Error:

> AADSTS75011: Authentication method 'MultiFactor, OneTimePasscode' by which the user authenticated with the service doesn't match requested authentication method 'Password, ProtectedTransport'.

My configuration to the saml is the following:
array(
        'security' => array(
            'strict' => true,
            'authnRequestsSigned' => false,
            'requestedAuthnContext' => false,
        ),
        // Service Provider Data that we are deploying.
        'sp' => array (
            'entityId' => '',
            'assertionConsumerService' => array (
                'url' => '',
                'binding' => 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST',
            ),
            'singleLogoutService' => array (
                'url' => '',
                'binding' => 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect',
            ),
            'NameIDFormat' => 'urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified',
            'x509cert' => 'My Cert',
            'privateKey' => 'My Key',
        ),

        // Identity Provider Data that we want connected with our SP.
        'idp' => array (
            // Identifier of the IdP entity  (must be a URI)
            'entityId' => '',
            // SSO endpoint info of the IdP. (Authentication Request protocol)
            'singleSignOnService' => array (
                'url' => '',
                'binding' => 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect',
            ),
            // SLO endpoint info of the IdP.
            'singleLogoutService' => array (
                'url' => '',
                'binding' => 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect',
            ),
            // Public x509 certificate of the IdP
            'x509cert' => 'IDP cert',
        ),

**Comment by aaronbach** [comment]
@djacobs-pewag do you have found a solution? I face this problem, since the activation of windows hello. Where do I can add this Authentication Method in the Settings. It is no Option to turn off windows hello on the Azure side.
Thx

**Comment by dam1r89** [comment]
Based on [this doc](https://learn.microsoft.com/en-us/troubleshoot/entra/entra-id/app-integration/error-code-AADSTS75011-auth-method-mismatch), the resolution would be to remove `RequestedAuthnContext` so, update the config like this
```
'security' => [
    'requestedAuthnContext' => false,
],
```
