### ISSUE TITLE
buildWithBaseURLPath return only last part of url

### ISSUE THREAD

**Issue by agrisvv** [SAML-Toolkits/php-saml#579]
Example of url
basepath: https://example.com/custom
assertion url: https://example.com/custom/login/idpname

Then function buildWithBaseURLPath returns:
https://example.com/custom/idpname

In result thow exception:
The response was received at https://example.com/custom/idpname instead of https://example.com/custom/login/idpname

Resolutions:
need to use all parts of url not only the last.

**Comment by joelpittet** [comment]
@agrisvv I am running into this exact issue too, thanks for posting it. 

I'll post a PR for a potential fix.
