### ISSUE TITLE
SAML Response not found, Only supported HTTP_POST Binding

### ISSUE THREAD

**Issue by pixiekat** [SAML-Toolkits/php-saml#599]
Why would this message come up in debug mode?

When I use saml tracer it comes back as a success in samlp:status

I see all the saml parameters returned and the actual parameters have post: Saml response.

**Comment by pitbulk** [comment]
Maybe you refreshed and you lost the POST data.

**Comment by pixiekat** [comment]
Hi - nothing was refreshed, it came directly from the server.

**Comment by pitbulk** [comment]
It came from the server, make sure you are doing a POST to the Assertion Consumer Service endpoint.

You can install [SAML Tracer](https://helpx.adobe.com/enterprise/kb/perform-a-saml-trace.html) to see what the IdP is sending and how.
